# Generated by Django 4.1.1 on 2022-11-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_book_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
